
# Set time zone
- name: Set time zone to that of SMIA (Europe/Oslo)
  ansible.builtin.timezone:
    name: Europe/Oslo

# Install and configure the web server.
- name: Install web server (nginx)
  package:
    name: nginx
    state: present

- name: Start and enable nginx service.
  systemd:
    name: nginx
    enabled: yes
    state: started

- name: Create a directory for the records
  ansible.builtin.file:
    path: '{{ content_path }}'
    state: directory
    mode: '0755'
    owner: '{{ record_script_user }}'
    group: '{{ record_script_user }}'
    setype: httpd_sys_content_t

- name: remove Debian's "sites-enabled/default" (so it doesn't fight our nginx config)
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  when: ansible_os_family == 'Debian'

- name: Deploy the nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/conf.d/serve_recordings.conf
  notify: Reload nginx



# Install ffmpeg and copy in the stream recorder script.

- name: Install ffmpeg
  ansible.builtin.include_tasks: install_ffmpeg.yml

- name: Deploy stream recording script
  template:
    src: stream_recorder.sh.j2
    dest: '{{ recorder_script_destination }}'
    mode: '0755'
    owner: '{{ record_script_user }}'
    group: '{{ record_script_user }}'



# Install and deploy the systemd-managed service for executing the recording script.

- name: Deploy systemd service file
  template:
    src: stream_recorder.service.j2
    dest: /etc/systemd/system/stream_recorder.service

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Enable and start service
  systemd:
    name: stream_recorder.service
    enabled: yes
    state: started
