services:
  icecast:
    build:
      context: ./icecast/
    environment:
      ADMIN_PASSWORD: hackme
      SOURCE_PASSWORD: hackme
      RELAY_PASSWORD: hackme
    ports:
      - 8000:8000
  liquidsoap:
    build:
      context: ./liquidsoap/
    environment:
      SOURCE_PASSWORD: hackme
      ICECAST_HOSTNAME: icecast
      ICECAST_PORT: 8000
      MOUNTPOINT_PASSWORD: hackme
    ports:
      - 8080-8085:8080-8085
    # volumes:
    #   - soundfiles:/mnt/liquidsoap
# volumes:
#   soundfiles: