services:
  icecast:
    build:
      context: ./icecast/
    restart: unless-stopped
    environment:
      ADMIN_PASSWORD: passwd
      SOURCE_PASSWORD: passwd
      RELAY_PASSWORD: passwd
    ports:
      - "8000:8000"
  liquidsoap:
    build:
      context: ./liquidsoap/
    restart: unless-stopped
    environment:
      SOURCE_PASSWORD: passwd
      ICECAST_HOSTNAME: icecast
      ICECAST_PORT: 8000
    volumes:
      - soundfiles:/mnt/liquidsoap
volumes:
  soundfiles: