name: Build Docker images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  TAG_ICECAST: ghcr.io/sleiphan/rr-streamer/icecast:latest
  TAG_LIQUIDSOAP: ghcr.io/sleiphan/rr-streamer/liquidsoap:latest

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Icecast image
      id: build_icecast
      run: |
        docker build -t ${{ env.TAG_ICECAST }} icecast/ > digest.txt
        echo "digest=$(cat digest.txt)" >> $GITHUB_OUTPUT
        cat $GITHUB_OUTPUT
        
    - name: Build the Liquidsoap image
      id: build_liquidsoap
      run: |
        docker build -t ${{ env.TAG_LIQUIDSOAP }} liquidsoap/ > digest.txt
        echo "digest=$(cat digest.txt)" > $GITHUB_OUTPUT
        cat $GITHUB_OUTPUT

    - name: Login to Github Container Registry (ghcr.io)
      if: github.event_name != 'pull_request'
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login -u ${{ github.actor }} ghcr.io --password-stdin
      
    - name: Push images to ghcr.io
      if: github.event_name != 'pull_request'
      run: |
        docker push ${{ env.TAG_ICECAST }}
        docker push ${{ env.TAG_LIQUIDSOAP }}
    
    # Install the cosign tool except on PR
    # https://github.com/sigstore/cosign-installer
    - name: Install cosign
      if: github.event_name != 'pull_request'
      uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 #v3.5.0
      with:
        cosign-release: 'v2.2.4'
    
    - name: Sign the published Docker image
      if: github.event_name != 'pull_request'
      env:
        TAGS: |
          ${{ env.TAG_ICECAST }}
          ${{ env.TAG_LIQUIDSOAP }}
        DIGEST: |
          ${{ steps.build_icecast.outputs.digest }}
          ${{ steps.build_liquidsoap.outputs.digest }}
      # This step uses the identity token to provision an ephemeral certificate
      # against the sigstore community Fulcio instance.
      run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
